In [ ]:
#比較103學年度和111學年度高中職列表差異

In [2]:
#輸出高中職列表
import pandas as pd

## 讓pd讀檔並切換語言參數
highSchool111 = pd.read_csv("high.csv")
highSchool111.head() #test

,代碼,學校名稱,公私立,縣市名稱,地址,電話,網址,備註
0,10301,國立華僑高級中等學校,公立,新北市,[220]新北市板橋區大觀路一段32號,(02)29684131,http://www.nocsh.ntpc.edu.tw,NaN
1,11301,私立淡江高中,私立,新北市,[251]新北市淡水區真理街26號,(02)26203850,http://www.tksh.ntpc.edu.tw,NaN
2,11302,私立康橋高中,私立,新北市,[231]新北市新店區華城路800號,(02)22166000,http://www.kcbs.ntpc.edu.tw,NaN
3,11306,私立金陵女中,私立,新北市,[241]新北市三重區重新路五段656號,(02)29956776,http://www.glghs.ntpc.edu.tw,NaN
4,11307,新北市裕德高級中等學校,私立,新北市,[236]新北市土城區擺接堡路1號,(02)82617889,http://www.yuteh.ntpc.edu.tw/,NaN

In [4]:
#輸出高中職列表
import pandas as pd

## 讓pd讀檔並切換語言參數
highSchool103 = pd.read_csv("high103.csv")
highSchool103.head() #test

,代碼,學校名稱,縣市名稱,地址,電話,網址,備註
0,10301,國立華僑中學,[01]新北市,[220]新北市板橋區大觀路一段32號,(02)29684131,http://www.nocsh.ntpc.edu.tw,NaN
1,11301,私立淡江高中,[01]新北市,[251]新北市淡水區真理街26號,(02)26203850,http://www.tksh.ntpc.edu.tw,NaN
2,11302,私立康橋高中,[01]新北市,[231]新北市新店區華城路800號,(02)22166000,http://www.kcbs.ntpc.edu.tw,NaN
3,11306,私立金陵女中,[01]新北市,[241]新北市三重區重新路五段656號,(02)29956776,http://www.glghs.ntpc.edu.tw,NaN
4,11309,財團法人南山高中,[01]新北市,[235]新北市中和區廣福路41號,(02)22492474,http://www.nssh.ntpc.edu.tw,NaN